"""create_users_table

Revision ID: ffdc0a98111c
Revises: 
Create Date: 2020-11-20 15:06:02.230689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name',sa.String(length=50),nullable=False),
    sa.Column('description',sa.String(length=255),nullable=False),
    sa.Column('image',sa.String(),nullable=False),
    sa.Column('price',sa.Float(),nullable=False),
    sa.Column('stock',sa.Integer(),nullable=False),
    sa.Column('category',sa.String(),nullable=False),
    sa.Column('create_at',sa.TIMESTAMP(),nullable=False),
    sa.Column('update_at',sa.TIMESTAMP(),nullable=False),
    sa.Column('owner_id',sa.Integer(),nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.ForeignKeyConstraint('owner_id','users.id')
    )
    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
