"""add created_at column to reviews table

Revision ID: a1b2c3d4e5f6
Revises: 4d2a35147412
Create Date: 2025-11-02 18:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '4d2a35147412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add created_at column to reviews table with NOT NULL and default
    # Using direct SQL for SQLite compatibility
    op.execute("""
        ALTER TABLE reviews 
        ADD COLUMN created_at DATETIME NOT NULL DEFAULT (datetime('now'))
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###

